
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter:      pygments
permalink:        pretty

title:            Tech Stuff
tagline:          Tales from the trenches 
url:              http://blog.pu-gh.com
paginate:         5
baseurl:          /
author:
  name:           Rhodri Pugh
  url:            https://twitter.com/rodnaph
  email:          rod@pu-gh.com

