# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Tech Stuff
tagline:          Tales from the trenches 
url:              http://blog.pu-gh.com
paginate:         1
baseurl:          /
author:
  name:           Rhodri Pugh
  url:            https://twitter.com/rodnaph
  email:          rod@pu-gh.com

