
markdown:         redcarpet
highlighter:      pygments
permalink:        pretty

title:            Tech Stuff
tagline:          Tales from the trenches 
url:              http://blog.pu-gh.com
paginate:         5
baseurl:          /
author:
  name:           Rhodri Pugh
  url:            https://twitter.com/rodnaph
  email:          rod@pu-gh.com

